// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unvxhbgcoraoxfjhapja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVudnhoYmdjb3Jhb3hmamhhcGphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzYxNjIsImV4cCI6MjA3MTc1MjE2Mn0.UD5I6xuxqFr8jau7ZQ5mQCRcnOXieNup7iiuBwloLns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});